Care_AI/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', views.home, name = 'home'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('form/', include('complianceform.urls')),
]

complianceform/urls.py
from django.urls import path
from django.conf.urls import url
from . import views, responses
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'complianceform'
urlpatterns = [
    path('principlelist/<int:principle_id>/<int:product_id>', views.principle_list, name= 'principle_list'),
    path('<int:principle_id>/complete', views.form_completed, name = 'form_completed'),
    path('form_changed', views.form_changed, name = 'form_changed'),
    path('JotFormID',views.JotFormID, name = 'JotFormID'),
    path('view/<int:product_id>/<int:entry_id>/', views.view_submissions, name = 'view_submissions'),
    path('analytics', views.analytics, name = 'analytics'),
    path('radar',views.radar, name = 'radar'),
    path('completeness_ranking',views.completeness_ranking, name = 'completeness_ranking'),
    path('number_ranking',views.number_ranking, name = 'number_ranking'),
    path('getNumberRanking/<str:group>/<str:audited>',responses.getNumberRanking, name = 'getNumberRanking'),
    path('radar_analytics',views.radar_analytics, name = 'radar_analytics'),
    path('getProductScores/<str:group>/<str:audited>', responses.getProductScores, name = 'getProductScores'),
    path('ranking_score/<str:group>/<str:audited>', responses.getRankingScores, name = 'ranking_score'),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'user'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name = 'logout'),
    path('register/', views.register ,name='register'),
    path('change_password/',views.change_password, name='change_password'),
    path('profile/', views.profile, name =  'profile'),
    path('profile/edit/', views.profile_edit,name = 'profile_edit'),
    path('products/', views.products, name = 'products'),
    path('products/register/', views.products_register, name = 'products_register'),
    path('products/<int:product_id>',views.product_edit, name = 'product_edit'),
    ]

complianceform/models.py
from django.db import models
from user.models import Products

class Questions(models.Model):
    description = models.TextField()
    in_principle = models.IntegerField()

class Versions(models.Model):
    online_date = models.DateField()


class VersionToQuestion(models.Model):
    version_id = models.ForeignKey(Versions,on_delete= models.CASCADE)
    question_id = models.ForeignKey(Questions,on_delete= models.CASCADE)
    class Meta:
        unique_together = ('version_id','question_id')

class Entries(models.Model):
    product_id = models.ForeignKey(Products,on_delete= models.CASCADE)
    version_id = models.ForeignKey(Versions,on_delete = models.CASCADE)
    entry_time = models.DateTimeField()
    principle = models.IntegerField()
    jotform_submission_id = models.CharField(max_length = 30)
    score = models.FloatField(null = True, default = 0)

class Answers(models.Model):
    entry_id = models.ForeignKey(Entries,on_delete=models.CASCADE)
    question_id = models.ForeignKey(Questions,on_delete = models.CASCADE)
    answers = models.TextField()

class JotFormIDs(models.Model):
    principle = models.IntegerField()
    jotform_id = models.CharField(max_length = 30)

    

complianceform/forms.py
from django import forms

#Model form for the JotFormIDs page
class JotFormIDForm(forms.Form):
    principle_1 = forms.CharField(label='Principle 1', max_length=14,required=False)
    principle_2 = forms.CharField(label='Principle 2', max_length=14,required=False)
    principle_3 = forms.CharField(label='Principle 3', max_length=14,required=False)
    principle_4 = forms.CharField(label='Principle 4', max_length=14,required=False)
    principle_5 = forms.CharField(label='Principle 5', max_length=14,required=False)
    principle_6 = forms.CharField(label='Principle 6', max_length=14,required=False)
    principle_7 = forms.CharField(label='Principle 7', max_length=14,required=False)
    principle_8 = forms.CharField(label='Principle 8', max_length=14,required=False)
    principle_9 = forms.CharField(label='Principle 9', max_length=14,required=False)
    principle_10 = forms.CharField(label='Principle 10', max_length=14,required=False)

complianceform/views.py
from django.shortcuts import render, get_object_or_404
from .models import Questions, Versions,VersionToQuestion,Entries,Answers,JotFormIDs
from user.models import Products,Scores
import requests
from datetime import date
from .forms import JotFormIDForm

#API KEY for the corresponding JotForm account
JFAPI_KEY = '7746a94a4b70e6826b90564723ec8049'

#Principle List
#This page generates the URL of the form with the corresponding principle
def principle_list(request,principle_id,product_id):
    request.session['product_id'] = product_id 
    product = get_object_or_404(Products,pk = product_id).__dict__
    oneToTen = range(1,11)

    #Get the form ID and the most recent entry
    form_ID = JotFormIDs.objects.get(principle = principle_id).jotform_id
    entries = Entries.objects.filter(product_id_id = product_id,principle = principle_id).order_by('-entry_time')

    #The base URL for the form
    url = 'https://form.jotformeu.com/jsform/' + form_ID + '?product_id=' + str(product_id)+'&username=' + str(request.user)
    if entries.count() != 0: #If there are previous entries
        entry_id = entries[0].id 
        previousAnswers = Answers.objects.filter(entry_id_id = entry_id)
        #Add the previous answers to the end of the URL to prepopulate the form
        for answer in previousAnswers:
            url += '&question_id_'+str(answer.question_id.id) + '=' + answer.answers
    

    args = {'url':url, 
            'productInfo':product,
            'oneToTen':oneToTen,
            'product_id':product_id}
    
    return render(request, 'embeded_form.html', args)


#This page is loaded as the Thank you page of each principle form
#This page loads the latest submission and store the answers
def form_completed(request, principle_id):
    product_id = request.session['product_id']
    product = get_object_or_404(Products,pk = product_id).__dict__
    form_ID = JotFormIDs.objects.get(principle = principle_id).jotform_id

    #Get the latest submissions from the corresponding form
    r = requests.get('https://eu-api.jotform.com/form/'+ form_ID +'/submissions?apiKey='+ JFAPI_KEY +'&orderby=created_at').json()['content']
    saveAnswer = []
    subFound = False
    rightSubmission = None
    oneToTen = range(1,11)
    args = {'productInfo':product,
            'oneToTen':oneToTen,
            'product_id':product_id}
    #Go through all the submissions
    for submission in r:
        #Check the fileds in each submission, until we find the one with the same username with the user
        for field in submission['answers'].values():
            if field['name'].lower().startswith('username') and field['answer'] == str(request.user):
                subFound = True
                rightSubmission = submission
                submissionID = submission['id']
                createdAt = submission['created_at']
                break
        if subFound == True:
            break

    #Debug message of there is no new submission from this user
    if not rightSubmission:
        args['message'] = 'No new submission'
        return render(request, 'form_completed.html', args)

    #Go through this submission's fields 
    for field in rightSubmission['answers'].values():
        #Fieldname starts with 'question_id_' is question fileds
        if field['name'].lower().startswith('question_id'):
            qpk = int(field['name'][12:])
            try:
                answer = field['answer']
            except:
                #Store an empty string if the anwser is empty, or it would store 'None'
                answer = ''

            #Append a list of qid and answer for later storing    
            saveAnswer.append([qpk,answer])

        #Store the version number and product_id
        elif field['name'].lower().startswith('version'):
            version = int(field['text'])
        elif field['name'].lower().startswith('product_id'):
            product_id = int(field['answer'])

    #Check if the entry already exists
    try:
        newEntry = Entries.objects.get(product_id_id = product_id, entry_time = createdAt+"-05:00")
        args['message'] = 'No new submission'
        return render(request,'form_completed.html', args)

    #Counting the number of questions answered and the total number of questions to calculate the completeness percentage
    #And then save the answers
    except:
        qCount = 0
        aCount = 0
        newEntry = Entries(product_id_id = product_id, version_id_id = version, entry_time = createdAt+"-05:00", jotform_submission_id = submissionID, principle = principle_id )
        newEntry.save()

        for qpk, answer in saveAnswer:
            qCount +=1
            if answer != '': aCount +=1 
            newAnswer = Answers(entry_id_id = newEntry.pk, question_id_id = qpk, answers = answer)
            newAnswer.save()
        newEntry.score = aCount/qCount
        newEntry.save()
        try:
            attrString = 'principle_'+ str(principle_id)
            saveScore = Scores.objects.get(product_id_id = product_id)
            setattr(saveScore, attrString , aCount/qCount)
            saveScore.save()
            
        except:
            attrString = 'principle_'+ str(principle_id)
            saveScore = Scores(product_id_id = product_id)
            setattr(saveScore, attrString , aCount/qCount)
            saveScore.save()
            
            
    args['message'] = 'Form Submitted. Please select another form on the left.'
    return render(request,'form_completed.html', args)


#Admin function, storing JotFormIDs
def JotFormID(request):
    if request.method == 'POST':
        form = JotFormIDForm(request.POST)
        if form.is_valid():
            #Save the IDs
            for i in range(1,11):
                try:
                    jfID = JotFormIDs.objects.get(principle = i)
                except:
                    jfID = JotFormIDs(principle =i)
                jfID.jotform_id = form.cleaned_data['principle_'+str(i)]
                jfID.save()

            message = "ID saved"
        else:
            message = "Invalid Form"

    else:
        #Prepopulate the form with current IDs
        formIDDict = {}
        for i in range(1,11):
            try:
                formIDDict['principle_'+str(i)] = JotFormIDs.objects.get(principle = i).jotform_id
            except:
                pass
        form = JotFormIDForm(formIDDict)
        message = ''

    return render(request, 'JotFormID.html', {'form': form, 'message':message})


#Admin function
#Check if the form changed
def form_changed(request):
    if request.method =='POST':
        form_IDs = JotFormIDs.objects.all()
        message=[]
        currentPrinciple = 0
        questionIDInThisVersion = []
        changeFormVersion =[]
        #Get a list of questions from the previous version
        try:
            previousVersionID = Versions.objects.latest('id').id
            questionIDInPreviousVersion = list(VersionToQuestion.objects.filter(version_id_id = previousVersionID).values_list('question_id_id',flat=True))
        except:
            #Empty list if this is the very first version
            questionIDInPreviousVersion = []
        
        #A dict of keywords which are not questions. To identify the question fields from the other.
        notQuestionNames = {
            'header': 'head',
            'header_default': 'principle',
            'submit button' : 'submit',
            'product id' : 'product',
            'version id' : 'version',
            'username': 'username'
        }
        # Iterate through the forms
        for ID in form_IDs:
            r = requests.get('https://eu-api.jotform.com/form/'+ID.jotform_id+'/questions?apiKey='+JFAPI_KEY).json()['content']
            currentPrinciple = ID.principle

            # Iterate through the items in each form response
            for content in r.values():
                message.append([currentPrinciple,content['name'],content['text'],content['qid']])

                # Only check if the name of the item starts with 'question_id_'
                # Excluding out heading, submit button, etc.
                if not content['name'].lower().startswith((tuple(notQuestionNames.values()))):
                    try:
                        #Check if the question already exists
                        newQuestion = Questions.objects.get(description = content['text'])
                        message.append('success')
                    except:
                        #or create a new question
                        newQuestion = Questions(description = content['text'], in_principle = currentPrinciple)
                        newQuestion.save() #Changes

                    #Change the field_id of the questions through the JotForm API
                    requests.post('https://eu-api.jotform.com/form/'+ID.jotform_id+'/question/'+content['qid']+'?apiKey='+JFAPI_KEY,
                                       data = {'question[name]' : 'question_id_'+ str(newQuestion.pk)}) 

                    message.append(newQuestion.pk)
                    questionIDInThisVersion.append(newQuestion.pk)

                elif content['name'].lower().startswith('version'):
                    #save the filed id for the version field for later, when posting back the new version id through the API 
                    changeFormVersion.append([ID.jotform_id,content['qid']])

        questionIDInPreviousVersion.sort()
        questionIDInThisVersion.sort()
        message.append(questionIDInPreviousVersion)
        message.append(questionIDInThisVersion)

        #Check if the previous version and the current version have the same questions
        if set(questionIDInPreviousVersion) != set(questionIDInThisVersion): #Changes
            #Create a new version and store the corresponding question id in VersionToQuestion
            newVersion = Versions(online_date = date.today())
            newVersion.save()

complianceform/templates/JotFormID.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Submit">
</form>
{{ message }}
{% endblock %}

complianceform/templates/analytics.html
{% extends 'base.html'%}
{% block content %}

<div class="row">
    <div class="col-sm-2">
<p><a href='/form/completeness_ranking'>Compliance Completeness Ranking</a></p>
<p><a href='/form/number_ranking'>Number of Products Ranking</a></p>
<p><a href='/form/radar_analytics'>Completeness Radar Chart</a></p>

</div>
<div class="col-sm-10">
    {% block chart %}
    {% endblock %}
</div>
</div>


{% endblock %}

complianceform/templates/completeness_ranking.html
{% extends 'analytics.html'%}
{% load static %}

{% block chart %}
{% load static %}
<meta charset="utf-8">

<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>


<!-- Create a div where the graph will take place -->
<body onload="DrawChart()">
  
<h1>Ranking</h1>
<p>Select a category:</p>
<select id="group_name" onchange="DrawChart()">
    <option value='All' selected="selected">All</option>
    <option value='Diagnostic'>Diagnostic</option>
    <option value='Therapeutic'>Therapeutic</option>
    <option value='Population health'>Population health</option>
    <option value='Care-based'>Care-based</option>
    <option value='Triage'>Triage</option>
    <option value='Self-care'>Selef-care</option>
    <option value='Health promotion' >Health promotion</option>
    <option value='Remote Monitoring'>Remote Monitoring</option>
    <option value='Remote Consultation'>Remote Consultation</option>
    <option value='Other'>Other</option>
</select>
<a>      </a>
<input type="checkbox" onclick="DrawChart()" id="audited" a/> Audited Only<br>
</body>
<p hidden='true' id='result'>No result</p>
<p></p>
<div class="rankGraph"></div>

<script src="{% static 'rankingBarChart.js' %}"></script>
<script>
  function DrawChart(){
    d3.select('.rankGraph').select("svg").remove();
    var urlmask = "{% url 'complianceform:ranking_score' group='gname' audited='auditedTrueOrFalse' %}"
    urlmask = urlmask.replace('gname',document.getElementById("group_name").value.toString())
    urlmask = urlmask.replace('auditedTrueOrFalse',document.getElementById("audited").checked.toString())
    d3.json(urlmask, function(error,data){
      console.log()
      if (Object.keys(data).length == 0){
        document.getElementById('result').hidden=false 
      } else {
        document.getElementById('result').hidden=true
        RankingBarChart('.rankGraph',data)
      }
  })
}
</script>

<style>
div.tooltip {	
    position: absolute;			
    text-align: center;			
    width: 30px;					
    height: 16px;					
    padding: 2px;				
    font: 12px sans-serif;		
    background: lightsteelblue;	
    border: 0px;		
    border-radius: 3px;			
    pointer-events: none;			
}
</style>

{% endblock %}

complianceform/templates/number_ranking.html
{% extends 'analytics.html'%}
{% block chart %}
<script src="https://d3js.org/d3.v4.js"></script>

<h1>Number of Products by Organisation (Top 10) </h1>

<p>Select a category:</p>
<select id="group_name" onchange="change_group()">
        <option value='All' selected="selected">All</option>
        <option value='Diagnostic'>Diagnostic</option>
        <option value='Therapeutic'>Therapeutic</option>
        <option value='Population health'>Population health</option>
        <option value='Care-based'>Care-based</option>
        <option value='Triage'>Triage</option>
        <option value='Self-care'>Selef-care</option>
        <option value='Health promotion' >Health promotion</option>
        <option value='Remote Monitoring'>Remote Monitoring</option>
        <option value='Remote Consultation'>Remote Consultation</option>
        <option value='Other'>Other</option>
</select>
<a>      </a>
<input type="checkbox" onclick="change_group()" id="audited" a/> Audited Only<br>
<div id='result'></div>
<p></p>


<script>
change_group()
function change_group(){
    var urlmask = "{% url 'complianceform:getNumberRanking' group='gname' audited='auditedTrueOrFalse' %}"
    urlmask = urlmask.replace('gname',document.getElementById("group_name").value.toString())
    urlmask = urlmask.replace('auditedTrueOrFalse',document.getElementById("audited").checked.toString())
    d3.json(urlmask, function(error,data){
        console.log(data)
        if (Object.keys(data).length == 0){
        document.getElementById('result').innerHTML='No Result'
        document.getElementById('result').hidden=false
      } else {
        document.getElementById('result').hidden=false
        document.getElementById('result').innerHTML=''
        function makeUL(array) {
    // Create the list element:
            var list = document.createElement('ol');

            for(var i = 0; i < array.length; i++) {
                // Create the list item:
                var item = document.createElement('li');

                // Set its contents:
                item.appendChild(document.createTextNode(array[i]['organisation'] +' : '+ array[i]['product_count'] + '  product(s)'));

                // Add it to the list:
                list.appendChild(item);
            }

            // Finally, return the constructed list:
            return list;
        }

            // Add the contents of options[0] to #foo:
            document.getElementById('result').appendChild(makeUL(data));
      }
    })
}

</script>

<ul>
{% for count in productCounts %}
    <li>No. {{ forloop.counter }} {{ count.organisation }} : {{ count.product_count  }} product{{count.product_count| pluralize:",s"}}</li>

{% endfor %}
</ul>
{% endblock %}

complianceform/templates/radar.html
<!DOCTYPE html>
{% extends 'principle_list.html'%}

<html>
		{% block embed %}
		{% load static %}
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

		<!-- Google fonts -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

		<!-- D3.js -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
		
		<style>			
			.legend {
				font-family: 'Raleway', sans-serif;
				fill: #333333;
			}
			
			.tooltip {
				fill: #333333;
			}
		</style>
	
	</head>
	<body>
		<h1>Radar Chart</h1>
		<div class="radarChart"></div>
		<script src="{% static 'radarChart.js' %}"></script>	
		<script>
      
      /* Radar chart design created by Nadieh Bremer - VisualCinnamon.com */
      
			////////////////////////////////////////////////////////////// 
			//////////////////////// Set-Up ////////////////////////////// 
			////////////////////////////////////////////////////////////// 

			var margin = {top: 100, right: 150, bottom: 100, left: 100},
				width = Math.min(900, window.innerWidth - 10) - margin.left - margin.right,
				height = Math.min(width, window.innerHeight - margin.top - margin.bottom - 20);
					
			////////////////////////////////////////////////////////////// 
			////////////////////////// Data ////////////////////////////// 
			////////////////////////////////////////////////////////////// 
			d3.json("{% url 'complianceform:getProductScores' group='False' audited='False' %}", function(scoreDict) { console.log(scoreDict) ;

			var data = [
					  [//User's Percentage
						{axis:"Principle 1",value: scoreDict[0]['principle_1']},
						{axis:"Principle 2",value: scoreDict[0]['principle_2']},
						{axis:"Principle 3",value: scoreDict[0]['principle_3']},
						{axis:"Principle 4",value: scoreDict[0]['principle_4']},
						{axis:"Principle 5",value: scoreDict[0]['principle_5']},
						{axis:"Principle 6",value: scoreDict[0]['principle_6']},
						{axis:"Principle 7",value: scoreDict[0]['principle_7']},
						{axis:"Principle 8",value: scoreDict[0]['principle_8']},
						{axis:"Principle 9",value: scoreDict[0]['principle_9']},
						{axis:"Principle 10",value: scoreDict[0]['principle_10']},
					  ],[//Total Percentage
					  	{axis:"Principle 1",value: scoreDict[1]['principle_1__avg']},
						{axis:"Principle 2",value: scoreDict[1]['principle_2__avg']},
						{axis:"Principle 3",value: scoreDict[1]['principle_3__avg']},
						{axis:"Principle 4",value: scoreDict[1]['principle_4__avg']},
						{axis:"Principle 5",value: scoreDict[1]['principle_5__avg']},
						{axis:"Principle 6",value: scoreDict[1]['principle_6__avg']},
						{axis:"Principle 7",value: scoreDict[1]['principle_7__avg']},
						{axis:"Principle 8",value: scoreDict[1]['principle_8__avg']},
						{axis:"Principle 9",value: scoreDict[1]['principle_9__avg']},
						{axis:"Principle 10",value: scoreDict[1]['principle_10__avg']},
					  ],
					  [//Group Percentage
					  	{axis:"Principle 1",value: scoreDict[2]['principle_1__avg']},
						{axis:"Principle 2",value: scoreDict[2]['principle_2__avg']},
						{axis:"Principle 3",value: scoreDict[2]['principle_3__avg']},
						{axis:"Principle 4",value: scoreDict[2]['principle_4__avg']},
						{axis:"Principle 5",value: scoreDict[2]['principle_5__avg']},
						{axis:"Principle 6",value: scoreDict[2]['principle_6__avg']},
						{axis:"Principle 7",value: scoreDict[2]['principle_7__avg']},
						{axis:"Principle 8",value: scoreDict[2]['principle_8__avg']},
						{axis:"Principle 9",value: scoreDict[2]['principle_9__avg']},
						{axis:"Principle 10",value: scoreDict[2]['principle_10__avg']},
					]];
			////////////////////////////////////////////////////////////// 
			//////////////////// Draw the Chart ////////////////////////// 
			////////////////////////////////////////////////////////////// 

			var color = d3.scale.ordinal()
				.range(["#12ab12","#EDC951","#CC333F"]);
				
			var radarChartOptions = {
			  w: width,
			  h: height,
			  margin: margin,
			  maxValue: 0.5,
			  levels: 5,
			  roundStrokes: false,
			  color: color
			};
			//Call function to draw the Radar chart
			RadarChart(".radarChart", data, radarChartOptions)});
		</script>
	</body>
{% endblock %}
</html>

complianceform/templates/radar_analytics.html
<!DOCTYPE html>
{% extends 'analytics.html'%}

<html>
		{% block chart %}
		{% load static %}
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

		<!-- Google fonts -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

		<!-- D3.js -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
		
		<style>			
			.legend {
				font-family: 'Raleway', sans-serif;
				fill: #333333;
			}
			
			.tooltip {
				fill: #333333;
			}
		</style>
	
	</head>
	<body>
		<h1>Radar Chart</h1>
		<script src="{% static 'radarChart.js' %}"></script>	
		<p>Select a category:</p>
			<select id="group_name" onchange="DrawRadarChart()">
				<option value='All' selected="selected">All</option>
				<option value='Diagnostic'>Diagnostic</option>
				<option value='Therapeutic'>Therapeutic</option>
				<option value='Population health'>Population health</option>
				<option value='Care-based'>Care-based</option>
				<option value='Triage'>Triage</option>
				<option value='Self-care'>Selef-care</option>
				<option value='Health promotion' >Health promotion</option>
				<option value='Remote Monitoring'>Remote Monitoring</option>
				<option value='Remote Consultation'>Remote Consultation</option>
				<option value='Other'>Other</option>
			</select>
			<a>      </a>
		<p>

		</p>
		<div class="radarChart"></div>
		<script>
		function DrawRadarChart() {
      
      /* Radar chart design created by Nadieh Bremer - VisualCinnamon.com */
      
			////////////////////////////////////////////////////////////// 
			//////////////////////// Set-Up ////////////////////////////// 
			////////////////////////////////////////////////////////////// 

			var margin = {top: 100, right: Math.min(100 ,window.innerWidth*0.18), bottom: 100, left: Math.min(100 ,window.innerWidth*0.18)},
				width = Math.min(900, window.innerWidth - 50) - margin.left - margin.right,
				height = Math.min(width, window.innerHeight - margin.top - margin.bottom - 20);
					
			////////////////////////////////////////////////////////////// 
			////////////////////////// Data ////////////////////////////// 
			////////////////////////////////////////////////////////////// 
			var urlmask = "{% url 'complianceform:getProductScores' group='gname' audited='auditedTrueOrFalse' %}"
    		urlmask = urlmask.replace('gname',document.getElementById("group_name").value.toString())
    		//urlmask = urlmask.replace('auditedTrueOrFalse',document.getElementById("audited").checked.toString())
			d3.json(urlmask, function(scoreDict) { console.log(scoreDict) ;

			var data = [[//Total Percentage
					  	{axis:"Principle 1",value: scoreDict[1]['principle_1__avg']},
						{axis:"Principle 2",value: scoreDict[1]['principle_2__avg']},
						{axis:"Principle 3",value: scoreDict[1]['principle_3__avg']},
						{axis:"Principle 4",value: scoreDict[1]['principle_4__avg']},
						{axis:"Principle 5",value: scoreDict[1]['principle_5__avg']},
						{axis:"Principle 6",value: scoreDict[1]['principle_6__avg']},
						{axis:"Principle 7",value: scoreDict[1]['principle_7__avg']},
						{axis:"Principle 8",value: scoreDict[1]['principle_8__avg']},
						{axis:"Principle 9",value: scoreDict[1]['principle_9__avg']},
						{axis:"Principle 10",value: scoreDict[1]['principle_10__avg']},
					  ],
					  [//Group Percentage
					  	{axis:"Principle 1",value: scoreDict[2]['principle_1__avg']},
						{axis:"Principle 2",value: scoreDict[2]['principle_2__avg']},
						{axis:"Principle 3",value: scoreDict[2]['principle_3__avg']},
						{axis:"Principle 4",value: scoreDict[2]['principle_4__avg']},
						{axis:"Principle 5",value: scoreDict[2]['principle_5__avg']},
						{axis:"Principle 6",value: scoreDict[2]['principle_6__avg']},
						{axis:"Principle 7",value: scoreDict[2]['principle_7__avg']},
						{axis:"Principle 8",value: scoreDict[2]['principle_8__avg']},
						{axis:"Principle 9",value: scoreDict[2]['principle_9__avg']},
						{axis:"Principle 10",value: scoreDict[2]['principle_10__avg']},
					]];
			////////////////////////////////////////////////////////////// 
			//////////////////// Draw the Chart ////////////////////////// 
			////////////////////////////////////////////////////////////// 

			var color = d3.scale.ordinal()
				.range(["#EDC951","#CC333F"]);
				
			var radarChartOptions = {
			  w: width,
			  h: height,
			  margin: margin,
			  maxValue: 0.5,
			  levels: 5,
			  roundStrokes: false,
			  color: color
			};
			//Call function to draw the Radar chart
			RadarChart(".radarChart", data, radarChartOptions)})};
		DrawRadarChart()
		</script>
		
	</body>
{% endblock %}
</html>